var CardAbilities = [
{
        title: "Fireball",
        proficiency: "Arcana",
        natural: 4,
        scale: 0.5,
        max: 8,
        reach: 5,
        will: 3,
        type: "ATTACK",
        sprite: 'Fireball.png',
        bullet: 'bullet.png'
    },
{
        title: "Poison Whip ",
        proficiency: "Arcana",
        natural: 2,
        scale: 2,
        max: 12,
        reach: 4,
        will: 5,
        type: "ATTACK",
        sprite: 'PoisonWhip.png',
        bullet: 'whip.png'
    },
{
        title: "Frost Lance",
        proficiency: "Arcana",
        natural: 6,
        scale: 1.5,
        max: 16,
        reach: 5,
        will: 5,
        type: "ATTACK",
        sprite: 'FrostLance.png',
        bullet: 'frostlance.png'
    },
{
        title: "Stone Skin",
        proficiency: "Arcana",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 0,
        will: 6,
        type: "SELF",
        sprite: 'StoneSkin.png',
        effect: "+1 and +1 for\nevery 3 Arcana to damage\nreduction permanently.",
        bullet: 'bullet.png'
    },
{
        title: "Waterweave",
        proficiency: "Arcana",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 5,
        will: 7,
        type: "SPELL",
        sprite: 'Waterweave.png',
        effect: "Heals 2 and\n+2 for every 3 Arcana to\nthe target's health.",
        bullet: 'heal.png'
    },
{
        title: "Lightning Step",
        proficiency: "Arcana",
        natural: 0,
        scale: 0.3,
        max: 0,
        reach: 3,
        will: 4,
        type: "SELF",
        sprite: 'LightningStep.png',
        effect: "+10 toward\nyour next roll and +1\nfor every 1 Clarity.",
        bullet: 'bullet.png'

    },
{
        title: "Geomancer",
        proficiency: "Arcana",
        natural: 10,
        scale: 1,
        max: 0,
        reach: 5,
        will: 7,
        type: "TRAP",
        sprite: 'Geomancer.png',
        effect: "Place a trap. Any\nunits who end turn on\ntrap will receive damage.",
        bullet: 'bullet.png'
    },

{
        title: "Gale",
        proficiency: "Arcana",
        natural: 6,
        scale: 0.5,
        max: 11,
        reach: 4,
        will: 5,
        type: "ATTACK",
        sprite: 'Gale.png',
        bullet: 'gale.gif'
    },
{
        title: "Cleave",
        proficiency: "Force",
        natural: 6,
        scale: 0.5,
        max: 16,
        reach: 2,
        will: 3,
        type: "ATTACK",
        sprite: 'Cleave.png',
        bullet: 'sword.png'
    },
{
        title: "Bloodlust",
        proficiency: "Force",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 0,
        will: 5,
        type: "SELF",
        sprite: 'Bloodlust.png',
        effect: "+2 and +1\nfor every 4 Force to\nyour next attack.",
        bullet: 'bullet.png'
    },
{
        title: "Frenzy",
        proficiency: "Force",
        natural: 4,
        scale: 0.5,
        max: 13,
        reach: 2,
        will: 4,
        type: "ATTACK",
        sprite: 'Frenzy.png',
        bullet: 'strike.png'
    },
{
        title: "Intrepid Strike",
        proficiency: "Force",
        natural: 8,
        scale: 1,
        max: 28,
        reach: 2,
        will: 9,
        type: "ATTACK",
        sprite: 'IntrepidStrike.png',
        bullet: 'firestrike.png'
    },
{
        title: "Offhand Blow",
        proficiency: "Force",
        natural: 2,
        scale: 1,
        max: 24,
        reach: 2,
        will: 6,
        type: "ATTACK",
        sprite: 'OffhandBlow.png',
        bullet: 'strike.png'
    },
{
        title: "Grapple",
        proficiency: "Force",
        natural: 4,
        scale: 0.5,
        max: 14,
        reach: 2,
        will: 4,
        type: "ATTACK",
        sprite: 'Grapple.png',
        bullet: 'firestrike.png'
    },
{
        title: "Dauntless Advance",
        proficiency: "Force",
        natural: 0,
        scale: 0.5,
        max: 0,
        reach: 2,
        will: 5,
        type: "SELF",
        sprite: 'DauntlessAdvance.png',
        effect: "+5 and\n+1 for every Force\ntoward your next roll.",
        bullet: 'bullet.png'
    },
{
        title: "Adanai's Embrace",
        proficiency: "Force",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 0,
        will: 4,
        type: "SELF",
        sprite: 'AdanaisEmbrace.png',
        effect: "Absorbs up\nto 2 and +1 for every\n3 Force damage. Expires\nafter you get attacked.",
        bullet: 'bullet.png'
    },
{
        title: "First Aid",
        proficiency: "Force",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 3,
        will: 6,
        type: "SPELL",
        sprite: 'Fireball.png',
        effect: "Heals 2 and\n+1 for every 3 Force to the\ntarget's health. +20% HP\nrecovery for one turn.",
        bullet: 'heal.png'

    },
{
        title: "Trueshot",
        proficiency: "Clarity",
        natural: 3,
        scale: 0.5,
        max: 13,
        reach: 6,
        will: 3,
        type: "ATTACK",
        sprite: 'Trueshot.png',
        bullet: 'arrow4.png'
    },
{
        title: "Skyfather's Arrow",
        proficiency: "Clarity",
        natural: 6,
        scale: 1,
        max: 26,
        reach: 8,
        will: 10,
        type: "ATTACK",
        sprite: 'SkyfathersArrow.png',
        bullet: 'arrow4.png'
    },
{
        title: "Nether Whisper",
        proficiency: "Clarity",
        natural: 4,
        scale: 1,
        max: 11,
        reach: 6,
        will: 8,
        type: "ATTACK",
        sprite: 'NetherWhisper.png',
        bullet: 'arrow4.png'
    },
{
        title: "Hail of Iron",
        proficiency: "Clarity",
        natural: 3,
        scale: 0.5,
        max: 10,
        reach: 6,
        will: 4,
        type: "ATTACK",
        sprite: 'HailyofIron.png',
        bullet: 'barrage.gif'
    },
{
        title: "Barrage",
        proficiency: "Clarity",
        natural: 4,
        scale: 1,
        max: 14,
        reach: 4,
        will: 6,
        type: "ATTACK",
        sprite: 'Barrage.png',
        bullet: 'barrage.gif'
    },
{
        title: "Windsplitter",
        proficiency: "Clarity",
        natural: 4,
        scale: 0.5,
        max: 11,
        reach: 7,
        will: 5,
        type: "ATTACK",
        sprite: 'Windsplitter.png',
        bullet: 'arrow3.png'
    },
{
        title: "Bushwack",
        proficiency: "Clarity",
        natural: 10,
        scale: 0.334,
        max: 0,
        reach: 3,
        will: 5,
        type: "TRAP",
        sprite: 'Bushwack.png',
        effect: "Place a trap. Any\nunits who end turn on\ntrap will receive damage.",
        bullet: 'arrow3.png'
    },
{
        title: "Oros' Blessing",
        proficiency: "Clarity",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 0,
        will: 4,
        type: "SELF",
        sprite: 'OrosBlessing.png',
        effect: "For this\nturn, all abilities gain 1\nand +1 for every 5\nClarity toward Reach.",
        bullet: 'bullet.png'
    },
{
        title: "Injection",
        proficiency: "Clarity",
        natural: 0,
        scale: 0,
        max: 0,
        reach: 4,
        will: 5,
        type: "SPELL",
        sprite: 'Fireball.png',
        effect: "+3 and +1\nfor every Clarity to\nthe target's next attack.",
        bullet: 'arrow4.png'
    }
    ];
var numOfCards = 0;

var myCards =[
    {
        card: null,
        slot: 1,
        x: 70,
        y: 490,
        button: null,
        removeButton: null,
        cardDesc: null,
        isPressed: false,
        cardView: null
    },
    {
        card: null,
        slot: 2,
        x: 170,
        y: 490,
        button: null,
        removeButton: null,
        cardDesc: null,
        isPressed: false,
        cardView: null
    },
    {
        card: null,
        slot: 3,
        x: 270,
        y: 490,
        button: null,
        removeButton: null,
        cardDesc: null,
        isPressed: false,
        cardView: null
    },
    {
        card: null,
        slot: 4,
        x: 370,
        y: 490,
        button: null,
        removeButton: null,
        cardDesc: null,
        isPressed: false,
        cardView: null
    },
    {
        card: null,
        slot: 5,
        x: 470,
        y: 490,
        button: null,
        removeButton: null,
        cardDesc: null,
        isPressed: false,
        cardView: null
    }
];


